### ISSUE TITLE
Multiple days?

### ISSUE THREAD

**Issue by benjivm** [dapd007/v-calendar-scheduler#11]
Can I not add events that span `n` number of days?

Current event:
```
events: [
          {
            date: new Date(),
            startTime: "13:00",
            endTime: "15:00",
          }
        ]
      }
```

I'd like to do this:
```
events: [
          {
            startDate: new Date(),
            endDate: new Date(),
            startTime: "13:00",
            endTime: "15:00",
          }
        ]
      }
```

**Comment by dapd007** [comment]
I'm sorry, but date ranges are not supported yet.

Also, this seems to be a duplicate of [#6](https://github.com/dapd007/v-calendar-scheduler/issues/6)

**Comment by benjivm** [comment]
@dapd007 Are you planning on implementing this?

**Comment by dapd007** [comment]
I might, but currently I really don't have the time to maintain the library.
Sorry.
